spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbs:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: gw20010406

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  level:
    root: info
    com.gewgblog.backend: debug
  file:
    name: log/blog-dev.log