spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbs:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8888

logging:
  level:
    root: warn
    com.gewgblog.backend: info
  file:
    name: log/blog-pro.log